add_lunch_combo eclipse_toro-userdebug
add_lunch_combo eclipse_grouper-userdebug
add_lunch_combo eclipse_d2vzw-userdebug
add_lunch_combo eclipse_toroplus-userdebug
add_lunch_combo eclipse_fascinatemtd-userdebug
